# Generated by Django 2.0.2 on 2018-03-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('aadhaar', models.CharField(max_length=100)),
                ('pancard', models.CharField(max_length=100)),
                ('hsc', models.CharField(max_length=100)),
                ('ssc', models.CharField(max_length=100)),
                ('cast_certificate', models.CharField(max_length=100)),
            ],
        ),
    ]
