# Generated by Django 2.0.2 on 2018-03-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dof_app', models.DateField(max_length=20, null=True)),
                ('status', models.IntegerField(default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=20, null=True)),
                ('job_description', models.CharField(max_length=20, null=True)),
                ('date_of_joining', models.DateField(max_length=20, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhaar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cast_certificate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hsc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pancard',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ssc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applied_jobs',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_job', to='SRS.jobs'),
        ),
        migrations.AddField(
            model_name='applied_jobs',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='SRS.user'),
        ),
    ]
