# Generated by Django 2.0.2 on 2018-03-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0002_auto_20180311_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_jobs',
            name='status',
            field=models.IntegerField(default='1'),
        ),
    ]
