# Generated by Django 2.0.2 on 2018-03-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0003_auto_20180311_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
