# Generated by Django 2.0.2 on 2018-03-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0006_auto_20180318_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRS.user'),
        ),
    ]
