# Generated by Django 2.0.2 on 2018-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0007_auto_20180318_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
